/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (bootstrap-icons.mjs).
 */
module.exports = {
  name: 'bootstrap-icons',
  mediaPlayer: {
    play: 'bi-play-circle',
    pause: 'bi-pause-circle',
    volumeOff: 'bi-volume-mute',
    volumeDown: 'bi-volume-down',
    volumeUp: 'bi-volume-up',
    settings: 'bi-gear',
    speed: 'bi-speedometer',
    language: 'bi-badge-cc',
    selected: 'bi-check',
    fullscreen: 'bi-fullscreen',
    fullscreenExit: 'bi-fullscreen-exit',
    bigPlayButton: 'bi-caret-right'
  }
}
