/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (eva-icons.mjs).
 */
module.exports = {
  name: 'eva-icons',
  mediaPlayer: {
    play: 'eva-play-circle-outline',
    pause: 'eva-pause-circle-outline',
    volumeOff: 'eva-volume-off-outline',
    volumeDown: 'eva-volume-down-outline',
    volumeUp: 'eva-volume-up-outline',
    settings: 'eva-settings-outline',
    speed: 'eva-flash-outline',
    language: 'eva-globe-outline',
    selected: 'eva-checkmark-outline',
    fullscreen: 'eva-expand-outline',
    fullscreenExit: 'eva-collapse-outline',
    bigPlayButton: 'eva-arrow-right-outline'
  }
}
