/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (fontawesome-v6-pro.mjs).
 */
module.exports = {
  name: 'fontawesome-v6-pro',
  mediaPlayer: {
    play: 'fal fa-play',
    pause: 'fal fa-pause',
    volumeOff: 'fal fa-volume-xmark',
    volumeDown: 'fal fa-volume-down',
    volumeUp: 'fal fa-volume-up',
    settings: 'fal fa-cog',
    speed: 'fal fa-running',
    language: 'fal fa-closed-captioning',
    selected: 'fal fa-check',
    fullscreen: 'fal fa-expand',
    fullscreenExit: 'fal fa-compress',
    bigPlayButton: 'fal fa-play'
  }
}
