/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (fontawesome-v6.mjs).
 */
module.exports = {
  name: 'fontawesome-v6',
  mediaPlayer: {
    play: 'fas fa-play',
    pause: 'fas fa-pause',
    volumeOff: 'fas fa-volume-xmark',
    volumeDown: 'fas fa-volume-low',
    volumeUp: 'fas fa-volume-high',
    settings: 'fas fa-gears',
    speed: 'fas fa-person-running',
    language: 'fas fa-closed-captioning',
    selected: 'fas fa-check',
    fullscreen: 'fas fa-expand',
    fullscreenExit: 'fas fa-compress',
    bigPlayButton: 'fas fa-play'
  }
}
