/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (ionicons-v4.mjs).
 */
module.exports = {
  name: 'ionicons-v4',
  mediaPlayer: {
    play: 'ion-md-play',
    pause: 'ion-md-pause',
    volumeOff: 'ion-md-volume-off',
    volumeDown: 'ion-md-volume-low',
    volumeUp: 'ion-md-volume-high',
    settings: 'ion-md-settings',
    speed: 'ion-md-flash',
    language: 'ion-logo-closed-captioning',
    selected: 'ion-md-checkmark',
    fullscreen: 'ion-md-expand',
    fullscreenExit: 'ion-md-contract',
    bigPlayButton: 'ion-md-play'
  }
}
