/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (line-awesome.mjs).
 */
module.exports = {
  name: 'line-awesome',
  mediaPlayer: {
    play: 'las la-play',
    pause: 'las la-pause',
    volumeOff: 'las la-volume-mute',
    volumeDown: 'las la-volume-down',
    volumeUp: 'las la-volume-up',
    settings: 'las la-cog',
    speed: 'las la-running',
    language: 'las la-closed-captioning',
    selected: 'las la-check',
    fullscreen: 'las la-expand',
    fullscreenExit: 'las la-compress',
    bigPlayButton: 'las la-play'
  }
}
