/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (material-icons.mjs).
 */
module.exports = {
  name: 'material-icons',
  mediaPlayer: {
    play: 'play_arrow',
    pause: 'pause',
    volumeOff: 'volume_off',
    volumeDown: 'volume_down',
    volumeUp: 'volume_up',
    settings: 'settings',
    speed: 'directions_run',
    language: 'closed_caption',
    selected: 'check',
    fullscreen: 'fullscreen',
    fullscreenExit: 'fullscreen_exit',
    bigPlayButton: 'play_arrow'
  }
}
