/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (mdi-v4.mjs).
 */
module.exports = {
  name: 'mdi-v4',
  mediaPlayer: {
    play: 'mdi-play',
    pause: 'mdi-pause',
    volumeOff: 'mdi-volume-off',
    volumeDown: 'mdi-volume-medium',
    volumeUp: 'mdi-volume-high',
    settings: 'mdi-settings',
    speed: 'mdi-run',
    language: 'mdi-closed-caption',
    selected: 'mdi-check',
    fullscreen: 'mdi-fullscreen',
    fullscreenExit: 'mdi-fullscreen-exit',
    bigPlayButton: 'mdi-play'
  }
}
