
/*
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its webfont counterpart (same filename without "svg-" prefix).
 * Edit that file instead (themify.mjs).
 */


const {
  tiControlPlay,
  tiControlPause,
  tiNa,
  tiVolume,
  tiSettings,
  tiDashboard,
  tiLayoutMediaOverlay,
  tiCheck,
  tiFullscreen,
  tiClose
} = require('@quasar/extras/themify')

module.exports = {
  name: 'svg-themify',
  mediaPlayer: {
    play: tiControlPlay,
    pause: tiControlPause,
    volumeOff: tiNa,
    volumeDown: tiVolume,
    volumeUp: tiVolume,
    settings: tiSettings,
    speed: tiDashboard,
    language: tiLayoutMediaOverlay,
    selected: tiCheck,
    fullscreen: tiFullscreen,
    fullscreenExit: tiClose,
    bigPlayButton: tiControlPlay
  }
}
