/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (themify.mjs).
 */
module.exports = {
  name: 'themify',
  mediaPlayer: {
    play: 'ti-control-play',
    pause: 'ti-control-pause',
    volumeOff: 'ti-na',
    volumeDown: 'ti-volume',
    volumeUp: 'ti-volume',
    settings: 'ti-settings',
    speed: 'ti-dashboard',
    language: 'ti-layout-media-overlay',
    selected: 'ti-check',
    fullscreen: 'ti-fullscreen',
    fullscreenExit: 'ti-close',
    bigPlayButton: 'ti-control-play'
  }
}
