/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (ionicons-v7.mjs).
 */
module.exports = {
  name: "ionicons-v7",
  mediaPlayer: {
    play: "ion-play",
    pause: "ion-pause",
    volumeOff: "ion-volume-mute",
    volumeDown: "ion-volume-low",
    volumeUp: "ion-volume-high",
    settings: "ion-settings",
    speed: "ion-speedometer",
    language: "ion-logo-closed-captioning",
    selected: "ion-checkmark",
    fullscreen: "ion-expand",
    fullscreenExit: "ion-contract",
    bigPlayButton: "ion-play",
  },
};
