/*
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its webfont counterpart (same filename without "svg-" prefix).
 * Edit that file instead (mdi-v4.mjs).
 */

module.exports = {
  name: "mdi-v4",
  mediaPlayer: {
    play: "mdi-play",
    pause: "mdi-pause",
    volumeOff: "mdi-volume-off",
    volumeDown: "mdi-volume-medium",
    volumeUp: "mdi-volume-high",
    settings: "mdi-settings",
    speed: "mdi-run",
    language: "mdi-closed-caption",
    selected: "mdi-check",
    fullscreen: "mdi-fullscreen",
    fullscreenExit: "mdi-fullscreen-exit",
    bigPlayButton: "mdi-play",
  },
};
