/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (uk.mjs).
 */
module.exports = {
  lang: "uk",
  mediaPlayer: {
    oldBrowserVideo:
      "Щоб переглянути це відео, увімкніть JavaScript та/або оновіть браузер до версії, що підтримує HTML5-відео.",
    oldBrowserAudio:
      "Щоб прослухати це аудіо, увімкніть JavaScript та/або оновіть браузер до версії, що підтримує HTML5-аудіо.",
    pause: "Пауза",
    play: "Відтворити",
    settings: "Налаштування",
    toggleFullscreen: "Повноекранний режим",
    mute: "Вимкнути звук",
    unmute: "Увімкнути звук",
    speed: "Швидкість відтворення",
    language: "Мова",
    playbackRate: "Швидкість відтворення",
    waitingVideo: "Очікування відео",
    waitingAudio: "Очікування аудіо",
    ratePoint5: "0.5x",
    rateNormal: "Нормальна",
    rate1Point5: "1.5x",
    rate2: "2x",
    trackLanguageOff: "Вимкнено",
    noLoadVideo: "Не вдалося завантажити відео",
    noLoadAudio: "Не вдалося завантажити аудіо",
    cannotPlayVideo: "Неможливо відтворити відео",
    cannotPlayAudio: "Неможливо відтворити аудіо",
  },
};
