/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (ar.mjs).
 */
module.exports = {
  lang: 'ar',
  mediaPlayer: {
    oldBrowserVideo: 'لمشاهدة الفيديو، يرجي تمكين جافا سكريبت و/أو قم بالتحديث الى متصفح يدعم خاصية صوت HTML5',
    oldBrowserAudio: 'للإستماع للصوت، يرجي تمكين جافا سكريبت و/أو قم بالتحديث الى متصفح يدعم خاصية صوت HTML5',
    pause: 'توقف',
    play: 'تشغيل',
    settings: 'إعدادات ',
    toggleFullscreen: 'تغيير للوضع الكامل للشاشة',
    mute: 'كتم الصوت',
    unmute: 'تفعيل الصوت',
    speed: 'معدل التشغيل', // Playback rate
    language: 'اللغه',
    playbackRate: 'معدل التشغيل',
    waitingVideo: 'إنتظار الفيديو',
    waitingAudio: 'إنتظار الصوت',
    ratePoint5: '.5x',
    rateNormal: 'عادي',
    rate1Point5: '1.5x',
    rate2: '2x',
    trackLanguageOff: 'إيقاف ',
    noLoadVideo: 'غير قادر على تحميل الفيديو',
    noLoadAudio: 'غير قادر على تحميل الصوت',
    cannotPlayVideo: 'تعذر تشغيل الفيديو',
    cannotPlayAudio: 'تعذر تشغيل الصوت'
  }
}
