/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (cs.mjs).
 */
module.exports = {
  lang: 'cs',
  mediaPlayer: {
    oldBrowserVideo: 'Pro zobrazení obrazu prosím zapněte JavaScript a/nebo zvažte aktualizaci na prohlížeč, který podporuje HTML5 audio.',
    oldBrowserAudio: 'Pro přehrání zvuku, prosím zapněte JavaScript a/nebo zvažte aktualizaci na prohlížeč, který podporuje HTML5 audio.',
    pause: 'Zastavit',
    play: 'Hrát',
    settings: 'Nastavení',
    toggleFullscreen: 'Přepni na celou obrazovku',
    mute: 'Vypnout zvuk',
    unmute: 'Zapnout zvuk',
    speed: 'Rychlost', // Playback rate
    language: 'Jazyk',
    playbackRate: 'Rychlost přehrávání',
    waitingVideo: 'Čekám na video',
    waitingAudio: 'Čekám na audio',
    ratePoint5: '.5x',
    rateNormal: 'Normálně',
    rate1Point5: '1.5x',
    rate2: '2x',
    trackLanguageOff: 'Vypnout',
    noLoadVideo: 'Nemůžu nahrát video',
    noLoadAudio: 'Nemůžu nahrát audio',
    cannotPlayVideo: 'Nemůžu přehrát video',
    cannotPlayAudio: 'Nemůžu přehrát audio'
  }
}
