/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (es.mjs).
 */
module.exports = {
  lang: 'es',
  mediaPlayer: {
    oldBrowserVideo: 'Para ver este video por favor active JavaScript y/o considere actualizar a un navegador que soporte video HTML5.',
    oldBrowserAudio: 'Para escuchar este audio por favor active JavaScript y/o considere actualizar a un navegador que soporte video HTML5.',
    pause: 'Pausa',
    play: 'Reproducir',
    settings: 'Ajustes',
    toggleFullscreen: 'Cambiar Pantalla Completa',
    mute: 'Silenciar',
    unmute: 'Desilenciar',
    speed: 'Velocidad', // Playback rate
    language: 'Idioma',
    playbackRate: 'Tasa de Reproducción',
    waitingVideo: 'Esperando por video',
    waitingAudio: 'Esperando por audio',
    ratePoint5: '.5x',
    rateNormal: 'Normal',
    rate1Point5: '1.5x',
    rate2: '2x',
    trackLanguageOff: 'Desactivado',
    noLoadVideo: 'Imposible cargar video',
    noLoadAudio: 'Imposible cargar audio',
    cannotPlayVideo: 'No se puede reproducir video',
    cannotPlayAudio: 'No se puede reproducir audio'
  }
}
