/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (sk.mjs).
 */
module.exports = {
  lang: 'sk',
  mediaPlayer: {
    oldBrowserVideo: 'Na zobrazenie obrazu prosím zapnite JavaScript a/alebo zvážtě aktualizáciu na prehliadač, ktorý podporuje HTML5 audio.',
    oldBrowserAudio: 'Na prehratie zvuku, prosím zapnite JavaScript a/alebo zvážtě aktualizáciu na prehliadač, ktorý podporuje HTML5 audio.',
    pause: 'Zastaviť',
    play: 'Hrať',
    settings: 'Nastavenia',
    toggleFullscreen: 'Prepni na celú obrazovku',
    mute: 'Vypnúť zvuk',
    unmute: 'Zapnúť zvuk',
    speed: 'Rýchlosť', // Playback rate
    language: 'Jazyk',
    playbackRate: 'Rýchlosť prehrávania',
    waitingVideo: 'Čakám na video',
    waitingAudio: 'Čakám na audio',
    ratePoint5: '.5x',
    rateNormal: 'Normálne',
    rate1Point5: '1.5x',
    rate2: '2x',
    trackLanguageOff: 'Vypnúť',
    noLoadVideo: 'Nemôžem nahrať video',
    noLoadAudio: 'Nemôžem nahrať audio',
    cannotPlayVideo: 'Nemôžem prehrať video',
    cannotPlayAudio: 'Nemôžem prehrať audio'
  }
}
