/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (sl.mjs).
 */
module.exports = {
  lang: 'sl',
  mediaPlayer: {
    oldBrowserVideo: 'Za ogled tega posnetka je potreben JavaScript. Prosim aktivirajte JavaScript in/ali razmislite o nadgradnji na brskalnik, ki podpira HTML5 video.',
    oldBrowserAudio: 'Za poslušanje tega posnetka je potreben JavaScript. Prosim aktivirajte JavaScript in/ali razmislite o nadgradnji na brskalnik, ki podpira HTML5 avdio.',
    pause: 'Premor',
    play: 'Predvajaj',
    settings: 'Nastavitve',
    toggleFullscreen: 'Preklop na celo-stranski prikaz',
    mute: 'Brez zvoka',
    unmute: 'Z zvokom',
    speed: 'Hitrost', // Playback rate
    language: 'Jezik',
    playbackRate: 'Hitrost predvajanja',
    waitingVideo: 'Čakam na video posnetek',
    waitingAudio: 'Čakam na zvočni posnetek',
    ratePoint5: '.5x',
    rateNormal: 'Normalno',
    rate1Point5: '1.5x',
    rate2: '2x',
    trackLanguageOff: 'Izklopi',
    noLoadVideo: 'Ne morem naložiti video posnetka',
    noLoadAudio: 'Ne morem naložiti zvočnega posnetka',
    cannotPlayVideo: 'Ne morem predvajati video posnetka',
    cannotPlayAudio: 'Ne morem predvajati zvočnega posnetka'
  }
}
