/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (zh-TW.mjs).
 */
module.exports = {
  lang: 'zh-TW',
  mediaPlayer: {
    oldBrowserVideo: '為觀看此視頻，請啟用 JavaScript 或考慮升級到支持 HTML5 視頻的瀏覽器。',
    oldBrowserAudio: '為收聽此音訊，請啟用 JavaScript 或考慮升級到支援 HTML5 音頻的瀏覽器。',
    pause: '暫停',
    play: '播放',
    settings: '設置',
    toggleFullscreen: '切換全屏',
    mute: '靜音',
    unmute: '取消靜音',
    speed: '播放速率', // Playback rate
    language: '語言',
    playbackRate: '回放速率',
    waitingVideo: '等待視頻中',
    waitingAudio: '等待音頻中',
    ratePoint5: '.5x',
    rateNormal: '正常',
    rate1Point5: '1.5x',
    rate2: '2x',
    trackLanguageOff: '關閉',
    noLoadVideo: '無法加載視頻',
    noLoadAudio: '無法加載音頻',
    cannotPlayVideo: '無法播放視頻',
    cannotPlayAudio: '無法播放音頻'
  }
}
